stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo 'Compiling the source code and generating artifacts.'
      displayName: 'Build Step'

- stage: Test
  jobs:
  - job: TestJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo 'Running unit tests and code quality checks.'
      displayName: 'Test Step'

- stage: Deploy
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo 'Deploying the application to a staging environment.'
      displayName: 'Deployment Step'

